// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters must be on same line or separate lines", Justification = "<Reviewed>", Scope = "member", Target = "~M:BashSoft.IO.Commands.ChangePathAbsoluteCommand.#ctor(System.String,System.String[],BashSoft.Contracts.IContentComparer,BashSoft.Contracts.IDatabase,BashSoft.Contracts.IDirectoryManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters must be on same line or separate lines", Justification = "<Reviewed>", Scope = "member", Target = "~M:BashSoft.IO.Commands.ChangePathRelativelyCommand.#ctor(System.String,System.String[],BashSoft.Contracts.IContentComparer,BashSoft.Contracts.IDatabase,BashSoft.Contracts.IDirectoryManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters must be on same line or separate lines", Justification = "<Reviewed>", Scope = "member", Target = "~M:BashSoft.IO.Commands.OrderAndTakeCommand.#ctor(System.String,System.String[],BashSoft.Contracts.IContentComparer,BashSoft.Contracts.IDatabase,BashSoft.Contracts.IDirectoryManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1117:Parameters must be on same line or separate lines", Justification = "<Reviewed>", Scope = "member", Target = "~M:BashSoft.IO.Commands.CompareFilesCommand.#ctor(System.String,System.String[],BashSoft.Contracts.IContentComparer,BashSoft.Contracts.IDatabase,BashSoft.Contracts.IDirectoryManager)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Contracts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1633:File must have header", Justification = "<Reviewed>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.IO.Commands")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Contracts")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.DataStructures")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Exceptions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.IO")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Judge")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Models")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.Repository")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1652:Enable XML documentation output", Justification = "<Reviewed>", Scope = "namespace", Target = "~N:BashSoft.StaticData")]